update hive config.

diff --git a/devops/hadoop/templates/hive-configmap.yaml b/devops/hadoop/templates/hive-configmap.yaml
--- a/devops/hadoop/templates/hive-configmap.yaml
+++ b/devops/hadoop/templates/hive-configmap.yaml
@@ -26,17 +26,42 @@ data:
     # Directory to find config artifacts
     # ------------------------------------------------------
 
-    CONFIG_DIR="/tmp/hive-config"
+    CONFIG_DIR="/tmp/hadoop-config"
+
+    # ------------------------------------------------------
+    # Copy config files from volume mount
+    # ------------------------------------------------------
+
+    for f in workers core-site.xml hdfs-site.xml mapred-site.xml yarn-site.xml; do
+      if [[ -e ${CONFIG_DIR}/$f ]]; then
+        cp ${CONFIG_DIR}/$f $HADOOP_HOME/etc/hadoop/$f
+      else
+        echo "ERROR: Could not find $f in $CONFIG_DIR"
+        exit 1
+      fi
+    done
+
+    # ------------------------------------------------------
+    # installing libraries if any
+    # (resource urls added comma separated to the ACP system variable)
+    # ------------------------------------------------------
+    cd $HADOOP_HOME/share/hadoop/common ; for cp in ${ACP//,/ }; do  echo == $cp; curl -LO $cp ; done; cd -
+
+    # ------------------------------------------------------
+    # Directory to find config artifacts
+    # ------------------------------------------------------
+
+    HIVE_CONFIG_DIR="/tmp/hive-config"
 
     # ------------------------------------------------------
     # Copy config files from volume mount
     # ------------------------------------------------------
 
     for f in hive-env.sh hive-site.xml; do
-      if [[ -e ${CONFIG_DIR}/$f ]]; then
-        cp ${CONFIG_DIR}/$f $HIVE_HOME/conf/$f
+      if [[ -e ${HIVE_CONFIG_DIR}/$f ]]; then
+        cp ${HIVE_CONFIG_DIR}/$f $HIVE_HOME/conf/$f
       else
-        echo "ERROR: Could not find $f in $CONFIG_DIR"
+        echo "ERROR: Could not find $f in $HIVE_CONFIG_DIR"
         exit 1
       fi
     done
